---
# Sample ansible playbook
- hosts: sib
  sudo: yes  
  gather_facts: false  

  tasks:
  - name: Check if shade module is installed
    command: pip show shade
    ignore_errors: true
    register: shade_installed
    changed_when: false

  - block:
      - name: install shade
        command: "pip install shade"
    when: shade_installed.rc != 0

  - name: Download cirros image
    get_url:
      url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
      dest: /tmp/cirros-0.3.4-x86_64-disk.img
  
  - name: Upload cirros image to openstack
    os_image:
      auth:                                                                                                                                                               
        auth_url: http://192.168.27.100/identity_v2_admin                                                                                                                 
        password: labstack                                                                                                                                                
        project_domain_id: default                                                                                                                                        
        project_name: admin                                                                                                                                               
        user_domain_id: default                                                                                                                                           
        username: admin  
      name: cirros
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /tmp/cirros-0.3.4-x86_64-disk.img
